# -*- coding: utf-8 -*-
"""Text_preprocessing_in_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlhXJPxsQLUBllgsWpgOZ95SlHfF1WfF

# Text Preprocessing and Linguistic Analysis in Natural Language Processing (NLP)

#### Natural Language Processing (NLP) is a field of AI that enables machines to understand, analyze, and derive meaning from human language. However, raw text data cannot be directly understood by machines. Hence the text must be preprocessed and linguistically analyzed

This focuses on the fundamental building blocks of NLP, which convert raw text into structured linguistic information. These steps help machines understand how text is formed, what each word represents, and how words relate to one another grammatically and semantically.
"""

# install necessary libraries

!pip install nltk spacy
!pip install -U spacy
!python -m spacy download en_core_web_sm

"""## Tokenization
#### Tokenization is the process of breaking text into smaller units called tokens.

* Sentence Tokenization: Splits text into sentences

* Word Tokenization: Splits sentences into individual words

##### Why it is needed: Machines process text word by word. Tokenization is the first step that transforms unstructured text into manageable units.
"""

import nltk
nltk.download('punkt')   #punkt -> sentance and word tokenizer model
nltk.download('punkt_tab') # punkt_tab -> new dependency required in recent nltk version
from nltk.tokenize import word_tokenize, sent_tokenize
# word_tokenize -> splits sentance into words and punctuations
# sent_tokenize -> split text into sentance

text= " Natural Language Processing is very Intresting."

print("Sentances:",sent_tokenize(text))
print("words:",word_tokenize(text))

"""## stop word removal
#### stopword : Stop words are commonly used words in a language that usually do not add significant meaning to a sentence.
* Eg (is, the,a, in, on, very) that usually do not add any meaning.


##### In most NLP tasks, these words:

* Appear very frequently

* Do not help in understanding the intent or topic
"""

# stop word removal
nltk.download('stopwords')

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
filterd_words=[w for w in word_tokenize(text) if w.lower() not in stop_words]

print(filterd_words)

"""## Lemmatization
#### Lemmatization is the process of converting words into their base or dictionary form, called a lemma.

Examples:

* running → run

* studies → study

Unlike stemming, lemmatization:

* Uses vocabulary and grammar rules

* Produces valid, meaningful words
"""

nltk.download('wordnet')
# wordnet is a lexical database used to find the base form of words

from nltk.stem import WordNetLemmatizer
lemmatizer= WordNetLemmatizer()
lemmatized = [lemmatizer.lemmatize(word.lower(),pos='v') for word in filterd_words]
print(lemmatized)

"""## Part of Speech Tagging

#### POS tagging assigns grammatical labels (noun, verb, adjective, etc.) to each word in a sentence.

Example:

* Apple → Noun

* opening → Verb

* office → Noun

##### Why it is needed: Understanding grammar helps machines infer meaning, detect relationships, and disambiguate words based on context.
"""

nltk.download('averaged_perceptron_tagger_eng')  #POS tagging

from nltk import pos_tag

# each word is tagged with its gramatical role

tokens = word_tokenize("Apple is opening a new office in india.")
print(pos_tag(tokens))

import spacy
nlp=spacy.load("en_core_web_sm")
doc = nlp("Apple is opening a new office in india.")
for token in doc:
    print(token.text,token.pos_)
for ent in doc.ents:
    print(ent.text, "->", ent.label_)